# Generated by Django 3.0.5 on 2020-04-13 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('avgAge', models.IntegerField()),
                ('avgDailyIncomeInUSD', models.IntegerField()),
                ('avgDailyIncomePopulation', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Covid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodType', models.CharField(max_length=120)),
                ('timeToElapse', models.IntegerField()),
                ('reportedCases', models.IntegerField()),
                ('population', models.IntegerField()),
                ('populatotalHospitalBedstion', models.IntegerField()),
                ('totalHospitalBeds', models.IntegerField()),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region', to='pai.Region')),
            ],
        ),
    ]
